import './global.css';

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
      </head>
      <body>
        <header>
          
        </header>
        {children}
        <footer className="absolute bottom-2 right-2">Copyright 2024 Mack Sawyer</footer>
      </body>
    </html>
  )
}
